/*
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.layer1.clients.java8.digital.api;

import com.layer1.clients.java8.digital.invoker.ApiException;
import com.layer1.clients.java8.digital.model.ApiError;
import com.layer1.clients.java8.digital.model.CreateBalanceExportRequest;
import com.layer1.clients.java8.digital.model.Export;
import com.layer1.clients.java8.digital.model.PaginatedExports;
import java.util.Set;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExportApi
 */
@Disabled
public class ExportApiTest {

    private final ExportApi api = new ExportApi();

    /**
     * Create a balance export
     *
     * Initiates a job to export balance data in the CSV format.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createBalanceExportTest() throws ApiException {
        CreateBalanceExportRequest createBalanceExportRequest = null;
        api.createBalanceExport(createBalanceExportRequest)
                .execute();
        // TODO: test validations
    }

    /**
     * Get export with a download link
     *
     * Retrieves export details with a short-lived download link by its ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getExportTest() throws ApiException {
        UUID id = null;
        Export response = api.getExport(id)
                .execute();
        // TODO: test validations
    }

    /**
     * List all exports
     *
     * Retrieves a paginated list of exports based on type and pagination settings.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getExportsTest() throws ApiException {
        Set<String> type = null;
        Integer pageNumber = null;
        Integer pageSize = null;
        List<PaginatedExports> response = api.getExports(type, pageNumber, pageSize)
                .execute();
        // TODO: test validations
    }

}
