/*
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.layer1.clients.java8.digital.api;

import com.layer1.clients.java8.digital.invoker.ApiException;
import com.layer1.clients.java8.digital.model.ApiError;
import com.layer1.clients.java8.digital.model.CreateKeyPairRequest;
import com.layer1.clients.java8.digital.model.KeyPair;
import com.layer1.clients.java8.digital.model.PaginatedResultKeyPair;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for KeyPairApi
 */
@Disabled
public class KeyPairApiTest {

    private final KeyPairApi api = new KeyPairApi();

    /**
     * Create key pair
     *
     * Creates a new key pair from which different addresses can be created
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createKeyPairTest() throws ApiException {
        CreateKeyPairRequest createKeyPairRequest = null;
        KeyPair response = api.createKeyPair(createKeyPairRequest)
                .execute();
        // TODO: test validations
    }

    /**
     * Get key pair
     *
     * Retrieve a key pair given id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getKeyPairTest() throws ApiException {
        UUID keyPairId = null;
        KeyPair response = api.getKeyPair(keyPairId)
                .execute();
        // TODO: test validations
    }

    /**
     * List key pairs
     *
     * Retrieve paginated list of key-pairs belonging to a asset pool
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listKeyPairsTest() throws ApiException {
        UUID assetPoolId = null;
        Integer pageNumber = null;
        Integer pageSize = null;
        PaginatedResultKeyPair response = api.listKeyPairs(assetPoolId, pageNumber, pageSize)
                .execute();
        // TODO: test validations
    }

}
