/*
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.layer1.clients.java8.digital.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.layer1.clients.java8.digital.invoker.JSON;

/**
 * CreateBalanceExportRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class CreateBalanceExportRequest {
  /**
   * network
   */
  @JsonAdapter(NetworkEnum.Adapter.class)
  public enum NetworkEnum {
    BASE("BASE"),
    
    BINANCE("BINANCE"),
    
    BITCOIN("BITCOIN"),
    
    BITCOIN_CASH("BITCOIN_CASH"),
    
    DOGECOIN("DOGECOIN"),
    
    ETHEREUM("ETHEREUM"),
    
    LITECOIN("LITECOIN"),
    
    POLYGON("POLYGON"),
    
    RIPPLE("RIPPLE"),
    
    SOLANA("SOLANA"),
    
    TRON("TRON"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    NetworkEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static NetworkEnum fromValue(String value) {
      for (NetworkEnum b : NetworkEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }

    public static class Adapter extends TypeAdapter<NetworkEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final NetworkEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public NetworkEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return NetworkEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      NetworkEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @Deprecated
  @SerializedName(SERIALIZED_NAME_NETWORK)
  @javax.annotation.Nullable
  private NetworkEnum network;

  public static final String SERIALIZED_NAME_ASSET = "asset";
  @Deprecated
  @SerializedName(SERIALIZED_NAME_ASSET)
  @javax.annotation.Nullable
  private String asset;

  /**
   * Gets or Sets networks
   */
  @JsonAdapter(NetworksEnum.Adapter.class)
  public enum NetworksEnum {
    BASE("BASE"),
    
    BINANCE("BINANCE"),
    
    BITCOIN("BITCOIN"),
    
    BITCOIN_CASH("BITCOIN_CASH"),
    
    DOGECOIN("DOGECOIN"),
    
    ETHEREUM("ETHEREUM"),
    
    LITECOIN("LITECOIN"),
    
    POLYGON("POLYGON"),
    
    RIPPLE("RIPPLE"),
    
    SOLANA("SOLANA"),
    
    TRON("TRON"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    NetworksEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static NetworksEnum fromValue(String value) {
      for (NetworksEnum b : NetworksEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }

    public static class Adapter extends TypeAdapter<NetworksEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final NetworksEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public NetworksEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return NetworksEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      NetworksEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_NETWORKS = "networks";
  @SerializedName(SERIALIZED_NAME_NETWORKS)
  @javax.annotation.Nullable
  private Set<NetworksEnum> networks = new LinkedHashSet<>();

  public static final String SERIALIZED_NAME_ASSETS = "assets";
  @SerializedName(SERIALIZED_NAME_ASSETS)
  @javax.annotation.Nullable
  private Set<String> assets = new LinkedHashSet<>();

  public static final String SERIALIZED_NAME_ASSET_POOL_ID = "assetPoolId";
  @SerializedName(SERIALIZED_NAME_ASSET_POOL_ID)
  @javax.annotation.Nullable
  private UUID assetPoolId;

  public CreateBalanceExportRequest() {
  }

  @Deprecated
  public CreateBalanceExportRequest network(@javax.annotation.Nullable NetworkEnum network) {
    this.network = network;
    return this;
  }

  /**
   * network
   * @return network
   * @deprecated
   */
  @Deprecated
  @javax.annotation.Nullable
  public NetworkEnum getNetwork() {
    return network;
  }

  @Deprecated
  public void setNetwork(@javax.annotation.Nullable NetworkEnum network) {
    this.network = network;
  }


  @Deprecated
  public CreateBalanceExportRequest asset(@javax.annotation.Nullable String asset) {
    this.asset = asset;
    return this;
  }

  /**
   * asset
   * @return asset
   * @deprecated
   */
  @Deprecated
  @javax.annotation.Nullable
  public String getAsset() {
    return asset;
  }

  @Deprecated
  public void setAsset(@javax.annotation.Nullable String asset) {
    this.asset = asset;
  }


  public CreateBalanceExportRequest networks(@javax.annotation.Nullable Set<NetworksEnum> networks) {
    this.networks = networks;
    return this;
  }

  public CreateBalanceExportRequest addNetworksItem(NetworksEnum networksItem) {
    if (this.networks == null) {
      this.networks = new LinkedHashSet<>();
    }
    this.networks.add(networksItem);
    return this;
  }

  /**
   * networks
   * @return networks
   */
  @javax.annotation.Nullable
  public Set<NetworksEnum> getNetworks() {
    return networks;
  }

  public void setNetworks(@javax.annotation.Nullable Set<NetworksEnum> networks) {
    this.networks = networks;
  }


  public CreateBalanceExportRequest assets(@javax.annotation.Nullable Set<String> assets) {
    this.assets = assets;
    return this;
  }

  public CreateBalanceExportRequest addAssetsItem(String assetsItem) {
    if (this.assets == null) {
      this.assets = new LinkedHashSet<>();
    }
    this.assets.add(assetsItem);
    return this;
  }

  /**
   * assets
   * @return assets
   */
  @javax.annotation.Nullable
  public Set<String> getAssets() {
    return assets;
  }

  public void setAssets(@javax.annotation.Nullable Set<String> assets) {
    this.assets = assets;
  }


  public CreateBalanceExportRequest assetPoolId(@javax.annotation.Nullable UUID assetPoolId) {
    this.assetPoolId = assetPoolId;
    return this;
  }

  /**
   * The ID of the asset pool for which the report will be generated.
   * @return assetPoolId
   */
  @javax.annotation.Nullable
  public UUID getAssetPoolId() {
    return assetPoolId;
  }

  public void setAssetPoolId(@javax.annotation.Nullable UUID assetPoolId) {
    this.assetPoolId = assetPoolId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CreateBalanceExportRequest instance itself
   */
  public CreateBalanceExportRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateBalanceExportRequest createBalanceExportRequest = (CreateBalanceExportRequest) o;
    return Objects.equals(this.network, createBalanceExportRequest.network) &&
        Objects.equals(this.asset, createBalanceExportRequest.asset) &&
        Objects.equals(this.networks, createBalanceExportRequest.networks) &&
        Objects.equals(this.assets, createBalanceExportRequest.assets) &&
        Objects.equals(this.assetPoolId, createBalanceExportRequest.assetPoolId)&&
        Objects.equals(this.additionalProperties, createBalanceExportRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(network, asset, networks, assets, assetPoolId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateBalanceExportRequest {\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("    networks: ").append(toIndentedString(networks)).append("\n");
    sb.append("    assets: ").append(toIndentedString(assets)).append("\n");
    sb.append("    assetPoolId: ").append(toIndentedString(assetPoolId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("network");
    openapiFields.add("asset");
    openapiFields.add("networks");
    openapiFields.add("assets");
    openapiFields.add("assetPoolId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateBalanceExportRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateBalanceExportRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateBalanceExportRequest is not found in the empty JSON string", CreateBalanceExportRequest.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("network") != null && !jsonObj.get("network").isJsonNull()) && !jsonObj.get("network").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `network` to be a primitive type in the JSON string but got `%s`", jsonObj.get("network").toString()));
      }
      // validate the optional field `network`
      if (jsonObj.get("network") != null && !jsonObj.get("network").isJsonNull()) {
        NetworkEnum.validateJsonElement(jsonObj.get("network"));
      }
      if ((jsonObj.get("asset") != null && !jsonObj.get("asset").isJsonNull()) && !jsonObj.get("asset").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `asset` to be a primitive type in the JSON string but got `%s`", jsonObj.get("asset").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("networks") != null && !jsonObj.get("networks").isJsonNull() && !jsonObj.get("networks").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `networks` to be an array in the JSON string but got `%s`", jsonObj.get("networks").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("assets") != null && !jsonObj.get("assets").isJsonNull() && !jsonObj.get("assets").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `assets` to be an array in the JSON string but got `%s`", jsonObj.get("assets").toString()));
      }
      if ((jsonObj.get("assetPoolId") != null && !jsonObj.get("assetPoolId").isJsonNull()) && !jsonObj.get("assetPoolId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `assetPoolId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("assetPoolId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateBalanceExportRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateBalanceExportRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateBalanceExportRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateBalanceExportRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateBalanceExportRequest>() {
           @Override
           public void write(JsonWriter out, CreateBalanceExportRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateBalanceExportRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             CreateBalanceExportRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateBalanceExportRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateBalanceExportRequest
   * @throws IOException if the JSON string is invalid with respect to CreateBalanceExportRequest
   */
  public static CreateBalanceExportRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateBalanceExportRequest.class);
  }

  /**
   * Convert an instance of CreateBalanceExportRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

