/*
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.layer1.clients.java8.digital.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.layer1.clients.java8.digital.model.Participant;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EstimateTransactionFeeRequest
 */
public class EstimateTransactionFeeRequestTest {
    private final EstimateTransactionFeeRequest model = new EstimateTransactionFeeRequest();

    /**
     * Model tests for EstimateTransactionFeeRequest
     */
    @Test
    public void testEstimateTransactionFeeRequest() {
        // TODO: test EstimateTransactionFeeRequest
    }

    /**
     * Test the property 'asset'
     */
    @Test
    public void assetTest() {
        // TODO: test asset
    }

    /**
     * Test the property 'network'
     */
    @Test
    public void networkTest() {
        // TODO: test network
    }

    /**
     * Test the property 'sources'
     */
    @Test
    public void sourcesTest() {
        // TODO: test sources
    }

    /**
     * Test the property 'destinations'
     */
    @Test
    public void destinationsTest() {
        // TODO: test destinations
    }

}
