/*
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.layer1.clients.java8.digital.api;

import com.layer1.clients.java8.digital.invoker.ApiCallback;
import com.layer1.clients.java8.digital.invoker.ApiClient;
import com.layer1.clients.java8.digital.invoker.ApiException;
import com.layer1.clients.java8.digital.invoker.ApiResponse;
import com.layer1.clients.java8.digital.invoker.Configuration;
import com.layer1.clients.java8.digital.invoker.Pair;
import com.layer1.clients.java8.digital.invoker.ProgressRequestBody;
import com.layer1.clients.java8.digital.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.layer1.clients.java8.digital.model.ApiError;
import com.layer1.clients.java8.digital.model.AssetValue;
import com.layer1.clients.java8.digital.model.EstimateTransactionFeeRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FeeApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public FeeApi() {
        this(Configuration.getDefaultApiClient());
    }

    public FeeApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call estimateTransactionFeeCall(@javax.annotation.Nonnull EstimateTransactionFeeRequest estimateTransactionFeeRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = estimateTransactionFeeRequest;

        // create path and map variables
        String localVarPath = "/digital/v1/fee-estimate";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "httpSignature", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call estimateTransactionFeeValidateBeforeCall(@javax.annotation.Nonnull EstimateTransactionFeeRequest estimateTransactionFeeRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'estimateTransactionFeeRequest' is set
        if (estimateTransactionFeeRequest == null) {
            throw new ApiException("Missing the required parameter 'estimateTransactionFeeRequest' when calling estimateTransactionFee(Async)");
        }

        return estimateTransactionFeeCall(estimateTransactionFeeRequest, _callback);

    }


    private ApiResponse<AssetValue> estimateTransactionFeeWithHttpInfo(@javax.annotation.Nonnull EstimateTransactionFeeRequest estimateTransactionFeeRequest) throws ApiException {
        okhttp3.Call localVarCall = estimateTransactionFeeValidateBeforeCall(estimateTransactionFeeRequest, null);
        Type localVarReturnType = new TypeToken<AssetValue>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call estimateTransactionFeeAsync(@javax.annotation.Nonnull EstimateTransactionFeeRequest estimateTransactionFeeRequest, final ApiCallback<AssetValue> _callback) throws ApiException {

        okhttp3.Call localVarCall = estimateTransactionFeeValidateBeforeCall(estimateTransactionFeeRequest, _callback);
        Type localVarReturnType = new TypeToken<AssetValue>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class APIestimateTransactionFeeRequest {
        @javax.annotation.Nonnull
        private final EstimateTransactionFeeRequest estimateTransactionFeeRequest;

        private APIestimateTransactionFeeRequest(@javax.annotation.Nonnull EstimateTransactionFeeRequest estimateTransactionFeeRequest) {
            this.estimateTransactionFeeRequest = estimateTransactionFeeRequest;
        }

        /**
         * Build call for estimateTransactionFee
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table border="1">
       <caption>Response Details</caption>
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 503 </td><td> Service Unavailable </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Standard error response </td><td>  -  </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Request invalid </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return estimateTransactionFeeCall(estimateTransactionFeeRequest, _callback);
        }

        /**
         * Execute estimateTransactionFee request
         * @return AssetValue
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table border="1">
       <caption>Response Details</caption>
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 503 </td><td> Service Unavailable </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Standard error response </td><td>  -  </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Request invalid </td><td>  -  </td></tr>
         </table>
         */
        public AssetValue execute() throws ApiException {
            ApiResponse<AssetValue> localVarResp = estimateTransactionFeeWithHttpInfo(estimateTransactionFeeRequest);
            return localVarResp.getData();
        }

        /**
         * Execute estimateTransactionFee request with HTTP info returned
         * @return ApiResponse&lt;AssetValue&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table border="1">
       <caption>Response Details</caption>
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 503 </td><td> Service Unavailable </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Standard error response </td><td>  -  </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Request invalid </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<AssetValue> executeWithHttpInfo() throws ApiException {
            return estimateTransactionFeeWithHttpInfo(estimateTransactionFeeRequest);
        }

        /**
         * Execute estimateTransactionFee request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table border="1">
       <caption>Response Details</caption>
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 503 </td><td> Service Unavailable </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Standard error response </td><td>  -  </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Request invalid </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<AssetValue> _callback) throws ApiException {
            return estimateTransactionFeeAsync(estimateTransactionFeeRequest, _callback);
        }
    }

    /**
     * Estimate transaction fee
     * Estimate fee to send blockchain transaction
     * @param estimateTransactionFeeRequest  (required)
     * @return APIestimateTransactionFeeRequest
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 503 </td><td> Service Unavailable </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Standard error response </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request invalid </td><td>  -  </td></tr>
     </table>
     */
    public APIestimateTransactionFeeRequest estimateTransactionFee(@javax.annotation.Nonnull EstimateTransactionFeeRequest estimateTransactionFeeRequest) {
        return new APIestimateTransactionFeeRequest(estimateTransactionFeeRequest);
    }
}
